name: Manual Trigger Example

on:
  # Allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your script
        run: |
          echo "Running the script"
