name: Run Automated Instagram Account App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment variables
        run: |
          echo "INSTA_USERNAME=${{ secrets.INSTA_USERNAME }}"
          echo "INSTA_PASSWORD=${{ secrets.INSTA_PASSWORD }}"

      - name: Run the script
        env:
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
        run: |
          python main.py
